export const ResList = [
  {
    id: "40377",
    resName: "Lucky Restaurant",
    cuisine: ["Biryani", "Tandoor"],
    avgRating: 4.3,
    delieveryTime: 36,
    costForTwo: "₹300 for two",
    imgId: "uvapcfajlsbctskdhuhl",
    location: "Santosh Nagar",
  },
  {
    id: "79706",
    resName: "Shah Ghouse Hotel & Restaurant",
    cuisine: ["Biryani", "Chinese", "Mughlai", "Tandoor"],
    avgRating: 4.4,
    delieveryTime: 30,
    costForTwo: "₹350 for two",
    imgId: "ggbuknqzqc4qoqfnl2cr",
    location: "Charminar",
  },

  {
    id: "650820",
    resName: "Imperial Multicuisine Restaurant",
    cuisine: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
    avgRating: 4.3,
    delieveryTime: 38,
    costForTwo: "₹400 for two",
    imgId: "rqlwvsmzcfxbg9u6ajgm",
    location: "Redhills",
  },
   {
    id: "403887",
    resName: "lala ka dhaba",
    cuisine: ["Biryani", "Tandoor"],
    avgRating: 4.3,
    delieveryTime: 36,
    costForTwo: "₹300 for two",
    imgId: "uvapcfajlsbctskdhuhl",
    location: "Santosh Nagar",
  },
  
   {
    id: "403782",
    resName: "Mehfil Restaurant",
    cuisine: ["Biryani", "Tandoor"],
    avgRating: 4.3,
    delieveryTime: 36,
    costForTwo: "₹300 for two",
    imgId: "uvapcfajlsbctskdhuhl",
    location: "Santosh Nagar",
  },
  {
    id: "77905",
    resName: "Santosh Dhaba Exclusive",
    cuisine: ["Biryani", "Chinese", "Italian", "Mexican", "Desserts"],
    avgRating: 4.3,
    delieveryTime: 45,
    costForTwo: "₹300 for two",
    imgId: "jllcesio37olflwnvter",
    location: "ABids",
  },
  {
    id: "289061",
    resName: "Istah - The Mediterranean Way",
    cuisine: [
      "Mediterranean",
      "Snacks",
      "Biryani",
      "Grill",
      "Kebabs",
      "Arabian",
      "Lebanese",
      "Beverages",
      "Desserts",
      "Italian",
    ],
    avgRating: 3.8,
    delieveryTime: 43,
    costForTwo: "₹250 for two",
    imgId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/4f3c4f02-b633-4afd-8ece-3f3a358741bc_289061.jpg",
    location: "Puppalaguda",
  },
];
// export default restaurantsArr;
